export { default as hotelLogo } from "./HotelLogo_transparent.png";
export { default as pic1 } from "./Room-3-p3.png";
export { default as pic2 } from "./Room-4-p1.png";
export { default as pic3 } from "./View-2.png";
export { default as pic4 } from "./Room-3-p1.png";
export { default as goldenApple } from "./golden_apple_96.png";
export { default as pigLingLogo } from "./pigLing_Logo_transparent.png";
export { default as bg009 } from "./background_009.png";

//product
export { default as animal1 } from "./sellItem/animal1.png";
export { default as animal2 } from "./sellItem/animal2.png";
export { default as animal3 } from "./sellItem/animal3.png";
export { default as animal4 } from "./sellItem/animal4.png";
export { default as animal5 } from "./sellItem/animal5.png";
export { default as animal6 } from "./sellItem/animal6.png";
export { default as animal7 } from "./sellItem/animal7.png";
export { default as animal8 } from "./sellItem/animal8.png";
// export { default as animal9 } from "./sellItem/animal9.png";
export { default as animal10 } from "./sellItem/animal10.png";
export { default as animal11 } from "./sellItem/animal11.png";
export { default as animal12 } from "./sellItem/animal12.png";
export { default as animal13 } from "./sellItem/animal13.png";
export { default as animal14 } from "./sellItem/animal14.png";
export { default as animal15 } from "./sellItem/animal15.png";
export { default as animal16 } from "./sellItem/animal16.png";
export { default as animal17 } from "./sellItem/animal17.png";
export { default as animal18 } from "./sellItem/animal18.png";

export { default as game1 } from "./sellItem/game1.png";
export { default as game2 } from "./sellItem/game2.png";
export { default as game3 } from "./sellItem/game3.png";
export { default as game4 } from "./sellItem/game4.png";
export { default as game5 } from "./sellItem/game5.png";
export { default as game6 } from "./sellItem/game6.png";
export { default as game7 } from "./sellItem/game7.png";
export { default as game8 } from "./sellItem/game8.png";
export { default as game9 } from "./sellItem/game9.png";

export { default as clothes1 } from "./sellItem/clothes1.png";
export { default as clothes2 } from "./sellItem/clothes2.png";
export { default as pant1 } from "./sellItem/pant1.png";
export { default as pant2 } from "./sellItem/pant2.png";
export { default as pant3 } from "./sellItem/pant3.png";
export { default as skirt1 } from "./sellItem/skirt1.png";
export { default as skirt2 } from "./sellItem/skirt2.png";
export { default as skirt3 } from "./sellItem/skirt3.png";
export { default as skirt4 } from "./sellItem/skirt4.png";
export { default as skirt5 } from "./sellItem/skirt5.png";
export { default as tshirt1 } from "./sellItem/tshirt1.png";
export { default as tshirt2 } from "./sellItem/tshirt2.png";
export { default as tshirt3 } from "./sellItem/tshirt3.png";
export { default as tshirt4 } from "./sellItem/tshirt4.png";

export { default as accessory1 } from "./sellItem/accessory1.png";
export { default as accessory2 } from "./sellItem/accessory2.png";
export { default as accessory3 } from "./sellItem/accessory3.png";
export { default as accessory4 } from "./sellItem/accessory4.png";
export { default as accessory5 } from "./sellItem/accessory5.png";
export { default as accessory6 } from "./sellItem/accessory6.png";
export { default as accessory7 } from "./sellItem/accessory7.png";
export { default as accessory8 } from "./sellItem/accessory8.png";
export { default as accessory9 } from "./sellItem/accessory9.png";
export { default as accessory10 } from "./sellItem/accessory10.png";
